### PR TITLE
VS2015 Extension

### PR DESCRIPTION
**Pull request by SJMakin**
Added VS2015 VSIX version of the extension.  So nice to see automatic unit test generation :+1: 

Resolves issue #3 

Will create another issue to make the common code between the extensions a library.  I found quite a few issues during my testing but most were not due to the port to VSIX and were problems in the 2010 code also.

### CODE REVIEW

**Comment by vinayaugustine** [comment]
It looks like you committed the bin\Debug folder to the repository.

@SJMakin: can you remove both the bin and obj directories?
@qxshower: If you add those directories to .gitignore in the repository root so they don’t show up (example from [SrcML.NET .gitignore]( https://github.com/abb-iss/SrcML.NET/blob/master/.gitignore)).

-V

**Comment by SJMakin** [comment]
I have removed the BIN/OBJ dirs as requested.  Apologies it took so long!!

**Comment by SJMakin** [comment]
I have updated the gitingore file as per the advice from @vinayaugustine

**Comment by SJMakin** [comment]
bump

**Comment by qxshower** [comment]
@SJMakin sorry I am on vacation. Will get back to you next week.

**Comment by aukaurea** [comment]
And then? There is no update since.

**Pull request merged**
